USE UNIVER  

SELECT PR1.SUBJECT[Предмет], PR1.NOTE[Оценка],
	(SELECT COUNT(*) FROM PROGRESS PR2
			WHERE PR1.NOTE=PR2.NOTE AND PR1.SUBJECT=PR2.SUBJECT) [Количество]
	FROM PROGRESS PR1
	GROUP BY PR1.NOTE,PR1.SUBJECT
	HAVING PR1.NOTE IN (8,9)

