--FULL OUTER JOIN

SELECT *
	 FROM PATIENTS INNER JOIN PATIENTS_ROOM
	ON PATIENTS.patient_room =PATIENTS_ROOM.room

SELECT *
	 FROM PATIENTS FULL OUTER JOIN PATIENTS_ROOM
	ON PATIENTS.patient_room =PATIENTS_ROOM.room

SELECT *
	 FROM PATIENTS_ROOM FULL OUTER JOIN PATIENTS
	ON  PATIENTS_ROOM.room =PATIENTS.patient_room

-- left/ right outer join

SELECT *
	 FROM PATIENTS LEFT OUTER JOIN PATIENTS_ROOM
	ON PATIENTS.patient_room =PATIENTS_ROOM.room

SELECT *
	 FROM PATIENTS RIGHT OUTER JOIN PATIENTS_ROOM
	ON PATIENTS.patient_room =PATIENTS_ROOM.room
