SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE Inner join AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE Inner join AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
								and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%'


SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE, AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT A1.AUDITORIUM, A2.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE AS A2, AUDITORIUM  AS A1
	WHERE A1.AUDITORIUM_TYPE = A2.AUDITORIUM_TYPE
								and A2.AUDITORIUM_TYPENAME LIKE '%компьютер%'