SELECT isnull( TEACHER.TEACHER_NAME, '***') [Преподаватель], PULPIT.PULPIT_NAME [Кафедра]
	FROM PULPIT LEFT OUTER JOIN TEACHER
		ON PULPIT.PULPIT= TEACHER.PULPIT

SELECT isnull( PULPIT.PULPIT_NAME, '***') [Кафедра],TEACHER.TEACHER_NAME[Преподаватель]
	FROM TEACHER LEFT OUTER JOIN PULPIT
		ON TEACHER.PULPIT = PULPIT.PULPIT

		 
SELECT isnull( PULPIT.PULPIT_NAME, '***') [Кафедра],TEACHER.TEACHER_NAME[Преподаватель]
	FROM TEACHER RIGHT OUTER JOIN PULPIT
		ON TEACHER.PULPIT = PULPIT.PULPIT

