SELECT PULPIT.PULPIT_NAME[Кафедра],FACULTY.FACULTY [Факультет],PROFESSION.PROFESSION_NAME [Специальность]
	FROM FACULTY,PULPIT, PROFESSION
	WHERE FACULTY.FACULTY = PULPIT.FACULTY
		and
			FACULTY.FACULTY=PROFESSION.FACULTY
		and
		PROFESSION_NAME In (SELECT PROFESSION.PROFESSION_NAME
							FROM PROFESSION
								WHERE ( PROFESSION.PROFESSION_NAME LIKE '%технологи%') )

--2-------

SELECT PULPIT.PULPIT_NAME[Кафедра],FACULTY.FACULTY [Факультет],PROFESSION.PROFESSION_NAME [Специальность]
	FROM FACULTY 
			Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
				
			Inner Join PROFESSION ON FACULTY.FACULTY=PROFESSION.FACULTY
	WHERE 
		PROFESSION_NAME In (SELECT PROFESSION.PROFESSION_NAME
							FROM PROFESSION
								WHERE ( PROFESSION.PROFESSION_NAME LIKE '%технологи%') )

--3------

SELECT PULPIT.PULPIT_NAME[Кафедра],FACULTY.FACULTY [Факультет],PROFESSION.PROFESSION_NAME [Специальность]
	FROM FACULTY 
			Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY		
			Inner Join PROFESSION ON FACULTY.FACULTY=PROFESSION.FACULTY
	WHERE ( PROFESSION.PROFESSION_NAME LIKE '%технологи%') 



