SELECT A.AUDITORIUM_CAPACITY [Вместимость ], A.AUDITORIUM_TYPE [Тип ]
	FROM AUDITORIUM as A
	WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY
										FROM AUDITORIUM A2
										WHERE A.AUDITORIUM_TYPE= A2.AUDITORIUM_TYPE
											ORDER BY AUDITORIUM_CAPACITY desc )
	Order by AUDITORIUM_CAPACITY desc;

SELECT FACULTY.FACULTY_NAME[Факультет]
		FROM FACULTY
			WHERE not exists (SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY)




